FROM python:3.6

RUN apt-get update && \
    apt-get install -y vim curl telnet locales-all && \
    apt-get clean

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8


COPY ./requirements.txt /opt/{{ project_name }}/

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r /opt/{{ project_name }}/requirements.txt

COPY . /opt/{{ project_name }}/

WORKDIR /opt/{{ project_name }}